user root;
worker_processes auto;
pcre_jit on;
daemon off;

env REDIS_PASSWORD;

error_log /dev/stdout warn;

events {
        multi_accept on;
        worker_connections 8192;
}

http {
        sendfile on;
        include mime.types;
        default_type application/octet-stream;
        resolver 127.0.0.11 valid=30s;

        map $http_upgrade $connection_upgrade {
                default upgrade;
                '' close;
        }

        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 60;
        types_hash_max_size 2048;
        client_max_body_size 1024M;

        server_tokens off;

        gzip on;
        gzip_vary on;
        gzip_min_length 1024;

        access_log /dev/stdout;

        upstream servers {
                server 127.0.0.1:8800;
                server 127.0.0.1:8801;
                server 127.0.0.1:8802;
                server 127.0.0.1:8803;
        }

        # charset utf-8;
        server {
                include listen.conf;

        error_page 497 = @handle_http_fallback;
        set $real_proto $scheme;

        location ~ ^/d/(?<id>[0-9a-z]+)/ {
        set $target_loc "";
        set $target_tok "";
        set $target_url "";
        set $target_uri "";
        set $target_uid "";

        rewrite_by_lua_file ngx_op_api_gateway_validate.luac;

        proxy_http_version 1.1;
        chunked_transfer_encoding on;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $real_proto;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Upgrade $http_upgrade;

        proxy_set_header X-ClientId $target_uid;

        proxy_set_header Cookie "";
        proxy_set_header User-Agent "";
        add_header Set-Cookie "";

        proxy_set_header Origin $target_url;
        proxy_set_header X-Token $target_tok;
        proxy_set_header Host $target_loc;

        proxy_pass $target_url$target_uri$is_args$args;

        proxy_request_buffering off;
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
        proxy_buffering off;
        }

        location ~ ^/api/|^/s$ {
        proxy_http_version 1.1;
        chunked_transfer_encoding on;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $real_proto;

        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Upgrade $http_upgrade;

        proxy_pass http://servers;

        proxy_request_buffering off;
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
        proxy_buffering off;
        }

        location @handle_http_fallback {
        if ($uri !~ ^/properties) {
                return 444;
        }
        set $real_proto "http";
        proxy_pass http://127.0.0.1:8123;
        }

        location / {
        root /var/www/html;
        index index.html;
        try_files $uri $uri/ =404;
        error_page 404 /404/index.html;
        }
        }
}

stream {
        resolver 127.0.0.11 valid=30s;

        server {
                include listen-control.conf;
        ssl_preread on;
        set $target_loc "";

        preread_by_lua_file ngx_op_webui_validate.luac;

        #proxy_buffer_size 0;
        proxy_next_upstream off;
        proxy_socket_keepalive on;
        proxy_connect_timeout 30s;
        proxy_pass $target_loc;
        }
}